import ast
import types
from pathlib import Path

import numpy as np
import pandas as pd
from PIL import Image


def _load_function_from_file(file_path: Path, func_name: str):
    src = file_path.read_text(encoding="utf-8")
    tree = ast.parse(src, filename=str(file_path))
    func_node = None
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and node.name == func_name:
            func_node = node
            break
    if func_node is None:
        raise AssertionError(f"Function {func_name} not found in {file_path}")

    mod = types.ModuleType("_extracted")
    # provide globals needed by the function
    mod.os = __import__("os")
    mod.np = np
    mod.pd = pd
    # tqdm wrapper for tests (no progress bar)
    mod.tqdm = lambda it, desc=None: it
    # DATASET_CLASSES will be injected by test

    code = compile(ast.Module(body=[func_node], type_ignores=[]), filename=str(file_path), mode="exec")
    exec(code, mod.__dict__)
    return mod, mod.__dict__[func_name]


class _MiniHFDataset:
    """Minimal HuggingFace-like dataset: supports len(), indexing, and slicing returning dict-of-lists."""

    def __init__(self, samples):
        self._samples = samples

    def __len__(self):
        return len(self._samples)

    def __getitem__(self, idx):
        if isinstance(idx, slice):
            items = self._samples[idx]
            out = {}
            for k in items[0].keys():
                out[k] = [it[k] for it in items]
            return out
        return self._samples[idx]


class _StubPipeline:
    def set_progress_bar_config(self, disable=True):
        return None

    def __call__(self, prompts, image, num_inference_steps, generator, height, width, callback=None, callback_steps=None):
        # Return one generated image per prompt
        imgs = []
        for _ in prompts:
            imgs.append(Image.new("RGB", (width, height), color=(255, 255, 255)))

        return types.SimpleNamespace(images=imgs)


class _StubAttributeEditor:
    def produceSelectedAttributes(self, vec):
        return np.asarray(vec)


class _StubPromptGenerator:
    def generatePrompt(self, vec):
        v = np.asarray(vec).astype(int).tolist()
        return f"PROMPT_{sum(v)}"


def test_generateFinalVal_writes_images_and_csv_with_vectors(tmp_path):
    run_stage_a_path = Path(__file__).resolve().parents[1] / "src" / "stage_a_generation" / "run_stage_a.py"
    mod, generateFinalVal = _load_function_from_file(run_stage_a_path, "generateFinalVal")

    # Provide DATASET_CLASSES for attribute name loading
    class DummyDatasetClass:
        def __init__(self, split="train"):
            self.listAllAttrib = ["hat", "bag", "pants", "shoes"]

    mod.DATASET_CLASSES = {"PA100k": DummyDatasetClass}

    # Build tiny dataset (HuggingFace-like)
    samples = []
    for i in range(3):
        samples.append(
            {
                "image": Image.new("RGB", (64, 64), color=(i, i, i)),
                "text": f"orig_{i}",
                "vector": [i % 2, 1, 0, 1],
            }
        )
    ds = _MiniHFDataset(samples)
    dataset = {"train": ds}

    args = types.SimpleNamespace(
        path_syn=str(tmp_path / "syn"),
        batch_size_memory=2,
        width=32,
        height=32,
        dataset_name="PA100k",
    )

    pipeline = _StubPipeline()
    attribute_editor = _StubAttributeEditor()
    prompt_generator = _StubPromptGenerator()

    seed = 123
    generateFinalVal(
        args=args,
        dataset=dataset,
        pipeline=pipeline,
        generator=None,
        attribute_editor=attribute_editor,
        prompt_generator=prompt_generator,
        seed=seed,
    )

    out_dir = tmp_path / f"syn_{seed}"
    assert out_dir.exists()

    cond_dir = out_dir / "condImgs"
    gen_dir = out_dir / "generatedImgs"
    assert cond_dir.exists() and gen_dir.exists()

    # Images should exist
    for i in range(3):
        assert (cond_dir / f"img-{i}.png").exists()
        assert (gen_dir / f"img-{i}.png").exists()

    # CSV should exist and have expected columns
    csv_path = out_dir / "generated.csv"
    assert csv_path.exists()

    df = pd.read_csv(csv_path)
    assert len(df) == 3
    assert set(["condImg", "genImg", "prompt"]).issubset(df.columns)

    # Vector columns should be present
    for name in ["hat", "bag", "pants", "shoes"]:
        assert f"{name}_gt" in df.columns
        assert f"{name}_sel" in df.columns

    # Prompts should be those generated by prompt_generator (PROMPT_{sum})
    assert df.loc[0, "prompt"].startswith("PROMPT_")
